version: '3.8'
services:
  server:
    build: ./
    command: ./wait-for-postgres.sh db ./server
    depends_on:
      - db
    ports:
      - 8000:8080
    environment:
      - DATABASE_DSN=host=db user=postgres dbname=really sslmode=disable
      - SERVER_HOST=:8080
      - DATABASE_PASSWORD=Kravchenko01
      - LOG_FILE_PATH=logfile

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    ports:
      - 5436:5432
    environment:
      - POSTGRES_PASSWORD=Kravchenko01

