version: '3.8'
services:
  server:
    build: ./
    command: ./server
    depends_on:
      - db
    ports:
      - 8000:8080
    environment:
      - DATABASE_DSN=host=db user=postgres password=Kravchenko01 dbname=really sslmode=disable

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    ports:
      - 5436:5432
    environment:
      - POSTGRES_PASSWORD=Kravchenko01

