version: '3.8'
services:
  server:
    build: ./
    command: ./wait-for-postgres.sh db ./server
    depends_on:
      - db
    ports:
      - 8000:8080
    env_file:
      - .env

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    ports:
      - 5436:5432
    env_file:
      - .env

